### ISSUE TITLE
No property of ”Table“， and "name 'OrderedDict' is not defined"?

### ISSUE THREAD

**Issue by Huaweidev** [logdog/asciiTable#2]
#### 1. No property of ”Table“ in asciitable module:
```
>>> dir(asciitable)
['AASTex', 'AASTexReader', 'AllType', 'BaseData', 'BaseHeader', 'BaseInputter', 'BaseOutputter', 'BaseReader', 'BaseSplitter', 'Basic', 'BasicReader', 'Cds', 'CdsReader', 'Column', 'CommentedHeader', 'CommentedHeaderReader', 'ContinuationLinesInputter', 'Daophot', 'DaophotReader', 'DefaultSplitter', 'DictLikeNumpy', 'FixedWidth', 'FixedWidthData', 'FixedWidthHeader', 'FixedWidthNoHeader', 'FixedWidthSplitter', 'FixedWidthTwoLine', 'FloatType', 'InconsistentTableError', 'IntType', 'Ipac', 'IpacReader', 'Keyword', 'Latex', 'LatexReader', 'Memory', 'MemoryReader', 'NoHeader', 'NoHeaderReader', 'NoType', 'NumType', 'NumpyOutputter', 'Rdb', 'RdbReader', 'StrType', 'Tab', 'TabReader', 'WhitespaceSplitter', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'basic', 'cds', 'convert_list', 'convert_numpy', 'core', 'daophot', 'fixedwidth', 'get_reader', 'get_writer', 'has_numpy', 'ipac', 'latex', 'latexdicts', 'memory', 'read', 'set_guess', 'ui', 'version', 'write']
```
#### 2. code in READ.MD should be:
`from asciitable import Table`

#### 3. "name 'OrderedDict' is not defined", is it correct for me to run this command?
```
>>> import collections
>>> import asciitable
>>> data = OrderedDict([('apple', [40,50,60,70]), ('banana', [3,1,2]), ('orange', [200]), ('pear', [8,8,90,7])])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'OrderedDict' is not defined
```

**Comment by logdog** [comment]
Sorry I was in a hurry and had a few typos. This is what I did and got it to work:
```
>>> from table import Table
>>> from collections import OrderedDict
>>> data = OrderedDict([('apple', [40,50,60,70]), ('banana', [3,1,2]), ('orange', [200]), ('pear', [8,8,90,7])])
>>> t = Table(data, max_total_width=90)
>>> t.show()
┌─────┬───┬───┬────┐
│apple│ban│ora│pear│
│     │ana│nge│    │
├─────┼───┼───┼────┤
│ 40  │ 3 │200│ 8  │
├─────┼───┼───┼────┤
│ 50  │ 1 │   │ 8  │
├─────┼───┼───┼────┤
│ 60  │ 2 │   │ 90 │
├─────┼───┼───┼────┤
│ 70  │   │   │ 7  │
└─────┴───┴───┴────┘

**Comment by Huaweidev** [comment]
>Quote：
 Sorry I was in a hurry and had a few typos. This is what I did and got it to work:

But i sitll got an error:
My version:
* OS Version: Microsoft Windows® 10 version1803
* Python Version: Python 3.7.2

```
# python3
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from table import Table
>>> from collections import OrderedDict
>>> data = OrderedDict([('apple', [40,50,60,70]), ('banana', [3,1,2]), ('orange', [200]), ('pear', [8,8,90,7])])
>>> t = Table(data, max_total_width=90)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'max_total_width'
```
and in Python2:
```
# python2
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from table import Table
>>> from collections import OrderedDict
>>> data = OrderedDict([('apple', [40,50,60,70]), ('banana', [3,1,2]), ('orange', [200]), ('pear', [8,8,90,7])])
>>> t = Table(data, max_total_width=90, fast_mode=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'fast_mode'
>>> t = Table(data, max_total_width=90)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'max_total_width'
```
